server:
  port: 8888
spring:
  datasource:
    druid:
      driver-class-name: ${trip.datasource.driver-class-name}
      username: ${trip.datasource.username}
      password: ${trip.datasource.password}
      url: jdbc:mysql://${trip.datasource.host}:${trip.datasource.port}/${trip.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
  profiles:
    active: dev

